/*
 * @Author: Jpeng
 * @Date: 2018-03-24 22:54:36 
 * @Last Modified by: Jpeng
 * @Last Modified time: 2018-04-04 14:42:43
 * @Email: peng8350@gmail.com 
 * @flow
 */

export const UPDATE_TAB = "UPDATE_TAB";

export const FETCH_GIRL_SUCCESS = "FETCH_GIRL_SUCCESS";

export const FETCH_GIRL_REQUESTING = "FETCH_GIRL_REQUESTING";

export const FETCH_GIRL_FAILED = "FETCH_GIRL_FAILED";

export const FETCH_GANK_SUCCESS = "FETCH_GANK_SUCCESS";

export const FETCH_GANK_REQUESTING = "FETCH_GANK_REQUESTING";

export const FETCH_GANK_FAILED = "FETCH_GANK_FAILED";

export const START_VIEWPIC = "START_VIEWPIC";

export const STOP_VIEWPIC = "STOP_VIEWPIC";

export const SETTING_CHANGEHEIGHT = "SETTING_CHANGEHEIGHT";

export const SETTING_CHANGENIGHT = "SETTING_CHANGENIGHT";

export const SETTING_CHANGEPOSITION = "SETTING_CHANGEPOSITION";

export const SETTING_CHANGEAUTOREFRESH = "SETTING_CHANGEAUTOREFRESH";

export const FETCH_HOME_GANK_REQUSTING = "FETCH_HOME_GANK_REQUSTING";

export const FETCH_HOME_GANK_SUCCESS = "FETCH_HOME_GANK_SUCCESS";

export const FETCH_HOME_GANK_FAILED = "FETCH_HOME_GANK_FAILED";
